-- ============================================================
-- CP Management - Database Schema Documentation
-- Backend: Google Sheets (via Google Apps Script)
-- Spreadsheet ID: 1-0ynE_WKgU58yok-uISHYiXeOHzughghhJf6vA_sdrs
-- ============================================================

-- 1. Users - ข้อมูลผู้ใช้งานระบบ
CREATE TABLE Users (
    username        VARCHAR(100) PRIMARY KEY,    -- ชื่อผู้ใช้ (unique)
    password        VARCHAR(100) NOT NULL,       -- รหัสผ่าน (plain text)
    displayName     VARCHAR(200) NOT NULL,       -- ชื่อแสดง / ชื่อตัวละคร
    role            VARCHAR(20)  NOT NULL DEFAULT 'member',  -- Super Admin | admin | member
    status          VARCHAR(20)  NOT NULL DEFAULT 'pending', -- active | inactive | pending
    profileImage    TEXT,                        -- Base64 encoded profile image (128x128 JPEG)
    weaponClass     VARCHAR(50),                 -- อาชีพ (One-handed Sword, Twin Sword, Staff, Wand, Orb, Two-handed Sword, Spear, Bow, Dagger, Rapier, Cannon)
    forceChangePassword BOOLEAN DEFAULT FALSE     -- บังคับเปลี่ยนรหัสผ่านหลัง reset
);

-- 2. Members - ข้อมูลสมาชิก CP
CREATE TABLE Members (
    id              VARCHAR(36)  PRIMARY KEY,    -- UUID (generated by Utilities.getUuid())
    name            VARCHAR(200) NOT NULL,       -- ชื่อสมาชิก / ชื่อตัวละคร
    cpValue         DECIMAL(10,2) NOT NULL DEFAULT 0,  -- ค่า CP ปัจจุบัน
    tier            VARCHAR(50),                 -- ชื่อ Tier ที่คำนวณจาก CP (auto-assigned)
    rewardPercent   DECIMAL(5,2) DEFAULT 0,      -- เปอร์เซ็นต์รางวัลจาก Tier (auto-assigned)
    status          VARCHAR(20)  NOT NULL DEFAULT 'active'  -- active | inactive | deleted
);

-- 3. CPTiers - ตั้งค่าช่วง CP และเปอร์เซ็นต์รางวัล
CREATE TABLE CPTiers (
    id              VARCHAR(36)  PRIMARY KEY,    -- UUID
    tierName        VARCHAR(50)  NOT NULL,       -- ชื่อ Tier (Bronze, Silver, Gold, ...)
    minCP           DECIMAL(10,2) NOT NULL,      -- CP ขั้นต่ำ
    maxCP           DECIMAL(10,2) NOT NULL,      -- CP สูงสุด
    rewardPercent   DECIMAL(5,2) NOT NULL DEFAULT 0,  -- เปอร์เซ็นต์รางวัล
    status          VARCHAR(20)  NOT NULL DEFAULT 'active'  -- active | deleted
    -- CONSTRAINT: minCP <= maxCP, no overlap between active tiers
);

-- 4. RewardDistributions - ประวัติการแจกรางวัล (header)
CREATE TABLE RewardDistributions (
    id              VARCHAR(36)  PRIMARY KEY,    -- UUID
    date            DATETIME     NOT NULL,       -- วันที่แจก
    totalPrize      DECIMAL(12,2) NOT NULL,      -- จำนวนเงินรางวัลรวม (บาท)
    distributedBy   VARCHAR(100) NOT NULL,       -- username ผู้แจก
    status          VARCHAR(20)  NOT NULL DEFAULT 'draft',  -- draft | confirmed | deleted
    note            TEXT                         -- หมายเหตุ
);

-- 5. RewardDetails - รายละเอียดการแจกรางวัลรายบุคคล
CREATE TABLE RewardDetails (
    id              VARCHAR(36)  PRIMARY KEY,    -- UUID
    distributionId  VARCHAR(36)  NOT NULL,       -- FK -> RewardDistributions.id
    memberId        VARCHAR(36)  NOT NULL,       -- FK -> Members.id
    memberName      VARCHAR(200) NOT NULL,       -- ชื่อสมาชิก (snapshot)
    cpValue         DECIMAL(10,2) NOT NULL,      -- CP ณ ขณะแจก (snapshot)
    tier            VARCHAR(50),                 -- Tier ณ ขณะแจก (snapshot)
    percentage      DECIMAL(5,2),                -- เปอร์เซ็นต์รางวัล ณ ขณะแจก (snapshot)
    amount          DECIMAL(12,2) NOT NULL       -- จำนวนเงินที่ได้รับ (บาท)
);

-- 6. LoginLogs - บันทึกการล็อกอิน
CREATE TABLE LoginLogs (
    timestamp       DATETIME     NOT NULL,       -- เวลาที่ล็อกอิน
    username        VARCHAR(100) NOT NULL,       -- ชื่อผู้ใช้ที่พยายามล็อกอิน
    action          VARCHAR(20)  NOT NULL        -- success | failed
);

-- 7. ActivityLogs - บันทึกกิจกรรมในระบบ
CREATE TABLE ActivityLogs (
    timestamp       DATETIME     NOT NULL,       -- เวลาที่เกิดกิจกรรม
    user            VARCHAR(100) NOT NULL,       -- username ผู้ทำ
    action          VARCHAR(50)  NOT NULL,       -- ชื่อ action (login, createMember, updateMember, ...)
    details         TEXT                         -- รายละเอียดเพิ่มเติม
);

-- 8. PasswordResets - คำขอรีเซ็ตรหัสผ่าน
CREATE TABLE PasswordResets (
    id              VARCHAR(36)  PRIMARY KEY,    -- UUID
    timestamp       DATETIME     NOT NULL,       -- เวลาที่ส่งคำขอ
    username        VARCHAR(100) NOT NULL,       -- username ที่ขอรีเซ็ต
    reason          TEXT,                        -- เหตุผลในการขอรีเซ็ต
    status          VARCHAR(20)  NOT NULL DEFAULT 'pending'  -- pending | approved | rejected
);

-- 9. Notifications - แจ้งเตือนสำหรับ Admin
CREATE TABLE Notifications (
    id              VARCHAR(36)  PRIMARY KEY,    -- UUID
    timestamp       DATETIME     NOT NULL,       -- เวลาที่สร้าง
    type            VARCHAR(30)  NOT NULL,       -- password_reset | register | info | warning
    title           VARCHAR(200) NOT NULL,       -- หัวข้อแจ้งเตือน
    message         TEXT         NOT NULL,       -- เนื้อหาแจ้งเตือน
    read            BOOLEAN      NOT NULL DEFAULT FALSE  -- อ่านแล้วหรือยัง
);

-- 10. Register - ข้อมูลการลงทะเบียน
CREATE TABLE Register (
    username        VARCHAR(100) PRIMARY KEY,    -- ชื่อผู้ใช้
    password        VARCHAR(100) NOT NULL,       -- รหัสผ่าน
    character_name  VARCHAR(200) NOT NULL,       -- ชื่อตัวละคร
    cp              DECIMAL(10,2) DEFAULT 0      -- CP เริ่มต้น
);

-- ============================================================
-- Relationships
-- ============================================================
-- RewardDetails.distributionId -> RewardDistributions.id
-- RewardDetails.memberId -> Members.id
-- Members.tier is auto-calculated from CPTiers based on cpValue
-- Users.username is referenced by ActivityLogs.user, LoginLogs.username
-- Register entries are copied to Users table on registration
